### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by notabene** [notabene/nota-bene.org-v7#15]
> Et dernier truc, après promis, j'arrête (pour aujourd'hui). Ta gestion de HTTPS est étrange.
> https://nota-bene.org est OK.
> https://www.nota-bene.org renvoie vers http://nota-bene.org
> Il serait bon de tout renvoyer vers https://nota-bene.org .

à creuser avec Nursit

**Comment by benchti** [comment]
mettre  https://nota-bene.org  dans "Adresse (URL) du site public" sur la page https://nota-bene.org/ecrire/?exec=configurer_identite

**Comment by notabene** [comment]
Merci Ben !
