### ISSUE TITLE
Faire un article sur les squelettes spip

### ISSUE THREAD

**Issue by notabene** [notabene/nota-bene.org-v7#6]
Dans `squelettes` j'ai mis `article.html` et `article-15.html`, et `article15.html` n'a jamais été appelé.

cf http://www.spip.net/fr_article3445.html

**Comment by benchti** [comment]
Penser à activer le plugin squelettes par rubrique ;) https://www.nursit.com/les-plugins-spip#squelettes_par_rubrique

**Comment by notabene** [comment]
Bon, nursit donc.
